#!/bin/bash

ansible gcp --become -m apt -a 'name=git state=present'
ansible gcp -m shell -a 'git --version'
ansible gcp --become -m apt -a 'name=git state=latest'
ansible gcp -m shell -a 'git --version'
ansible gcp --become -m apt -a 'name=git state=absent'
ansible gcp -m shell -a 'git --version || echo git not found'
