#!/bin/bash

set -euxo pipefail

ansible gcp --become -m apt_repository -a 'repo=ppa:git-core/ppa'
ansible gcp --become -m apt -a 'name=git state=latest'
ansible gcp --become -m file -a '
  dest=/app
  state=directory
  owner=steshaw
  group=steshaw
'
ansible gcp -m git -a '
  repo=https://github.com/steshaw/scotty-example.git
  dest=/app
  version=HEAD
  force=yes
'
ansible gcp -m shell -a '
  executable=/bin/bash
  set -euxo pipefail
  git --version
  cd /app
  echo "epoch of stack.yaml = $(git log -1 --pretty=tformat:%ad --date=unix stack.yaml)"
'
ansible gcp -m shell -a 'echo "-- fooey" >>/app/Main.hs'
ansible gcp -m shell -a '
  echo ----------
  pwd
  ls
  echo ----------
  cd /app
  ls
  git status
'
