#!/bin/bash

set -euxo pipefail

ansible gcp --become -m apt -a 'name=git state=latest'
ansible gcp --become -m file -a '
  dest=/app
  state=directory
  owner=steshaw
  group=steshaw
'
ansible gcp -m git -a '
  repo=https://github.com/steshaw/scotty-example.git
  dest=/app
  version=HEAD
  force=yes
'
ansible gcp -m shell -a 'echo "-- fooey" >>/app/Main.hs'
ansible gcp -m shell -a '
  echo ----------
  pwd
  ls
  echo ----------
  cd /app
  ls
  git status
'
